title:             dydtjr1128's Blog
email:             dydtjr1994@gmail.com
description:       공부하는 개발자 블로그
author:            Start Bootstrap
baseurl:           "/"
url:               "https://dydtjr1128.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   dydtjr1128
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
