title:             Clean Blog
email:             dydtjr1994@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/"
url:               "http://dydtjr1128.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   dydtjr1128
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
