title:             dydtjr1128's Blog
email:             dydtjr1994@gmail.com
description:       공부하는 개발자 블로그
author:            dydtjr1128
baseurl:           "/"
url:               "https://dydtjr1128.github.io"

# Social Profiles

github_username:   dydtjr1128

disqus_url:
disqus_id : dydtjr1128
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
